# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       keychain

# >> macros
# << macros

Summary:    agent manager for OpenSSH, ssh.com, Sun SSH, and GnuPG
Version:    2.8.5
Release:    0
Group:      Applications/Internet
License:    GPL v2
BuildArch:  noarch
URL:        http://www.funtoo.org
Source0:    %{name}-%{version}.tar.gz
Source100:  keychain.yaml
BuildRequires:  perl

%description
Keychain is a manager for OpenSSH, ssh.com, Sun SSH and GnuPG agents.
It acts as a front-end to the agents, allowing you to easily have one
long-running agent process per system, rather than per login session.
This reduces the number of times you need to enter your passphrase
from once per new login session to once every time your local machine
is rebooted.

%if "%{?vendor}" == "chum"
Type: console-application
PackagerName: nephros
Categories:
 - Utility
Custom:
  PackagingRepo: https://gitlab.com/nephros/openrepos-keychain
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
make keychain
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
%{__install} -m 755 -D keychain $RPM_BUILD_ROOT/%{_bindir}/%{name}
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/*
# >> files
# << files
