# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       keychain

# >> macros
# << macros

Summary:    Agent manager for OpenSSH, ssh.com, Sun SSH, and GnuPG
Version:    2.8.5
Release:    2
Group:      Applications/Internet
License:    GPLv2
BuildArch:  noarch
URL:        https://www.funtoo.org/Keychain
Source0:    %{name}-%{version}.tar.gz
Source100:  keychain.yaml
BuildRequires:  perl
Provides:   openrepos-keychain = %{version}
Conflicts:   openrepos-keychain <= %{version}
Obsoletes:   openrepos-keychain < %{version}

%description
Keychain is a manager for OpenSSH, ssh.com, Sun SSH and GnuPG agents.
It acts as a front-end to the agents, allowing you to easily have one
long-running agent process per system, rather than per login session.
This reduces the number of times you need to enter your passphrase
from once per new login session to once every time your local machine
is rebooted.

%if "%{?vendor}" == "chum"
Type: console-application
PackagerName: nephros
Categories:
 - Security
 - ConsoleOnly
 - Utility
Custom:
  Repo: https://github.com/funtoo/keychain
  PackagingRepo: https://github.com/sailfishos-chum/keychain
Url:
  Homepage: https://www.funtoo.org/Keychain
  Help: https://www.funtoo.org/Keychain
  Bugtracker: https://github.com/funtoo/keychain/issues
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
make keychain
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
%{__install} -m 755 -D keychain $RPM_BUILD_ROOT/%{_bindir}/%{name}
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/*
# >> files
# << files
